global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
 - rules.yml
alerting:
 alertmanagers:
 - static_configs:
   - targets:
      - localhost:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:8000
       - localhost:9090
       - 192.168.1.181:9090
       - 192.168.1.183:9090
       - 192.168.1.184:9090
 - job_name: node
   static_configs:
    - targets:
       - localhost:9100
       - 192.168.1.181:9100
       - 192.168.1.183:9100
       - 192.168.1.184:9100
